#!/bin/sh

uci -q batch <<'EOF'
set network.lan.proto='dhcp'
delete network.lan.ipaddr
delete network.lan.netmask
delete network.lan.gateway
delete network.lan.dns
delete network.lan.ip6assign
delete network.wan
delete network.wan6

set dhcp.lan.ignore='1'
set dhcp.lan.ra='disabled'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ndp='disabled'

set system.@system[0].hostname='OneCloud'
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'

commit network
commit dhcp
commit system
EOF

exit 0
