#!/bin/sh

uci -q batch <<'EOF'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.10.2'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.10.1'
delete network.lan.dns
add_list network.lan.dns='192.168.10.1'
delete network.wan
delete network.wan6

set dhcp.lan.ignore='1'
set dhcp.lan.ra='disabled'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ndp='disabled'

set system.@system[0].hostname='OneCloud'
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'

commit network
commit dhcp
commit system
EOF

exit 0
